FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["K8SDemo.csproj", "K8SDemo/"]
RUN dotnet restore "K8SDemo/K8SDemo.csproj"
COPY . /src/DockerTest
WORKDIR /src/DockerTest
RUN dotnet build "K8SDemo.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "K8SDemo.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "K8SDemo.dll"]

