version: '3'
services:
  db:
    image: mysql
    container_name: 'db'
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: yanh
      MYSQL_PASSWORD: 123
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    volumes:
      - /e/docker/mysqlcompose/mysql-init:/docker-entrypoint-initdb.d
      - /e/docker/mysqlcompose/data:/var/lib/mysql
    networks:
       - my-bridge
  web:
    build: 
      context: .
      dockerfile: Dockerfile  #指定使用的Dockerfile
    container_name: 'myaspnetcore'
    ports:
       - '8000:80'
    depends_on:
       - db
    volumes:
       - /e/docker/mysqlcompose/appsettings.json:/app/appsettings.json
    networks:
       - my-bridge
networks:
  my-bridge: #创建名为mybridge的network
    driver: bridge

